title: Britannica Code
description: Britannica Code is the tech blog of a professional British software developer placed on this Earth to de-mystify technology alongside a dry wit.

timezone: Europe/London
lang: EN
locale: en_GB

baseurl: ""
url: "aidlran.github.io"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme

markdown: kramdown

# theme: minima
remote_theme: jekyll/minima

author:
  name: Aidan Loughran
  email: aidlo.dev@pm.me

minima:
  skin: dark
  social_links:
    twitter: aidlran
    github: aidlran

show_excerpts: true

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Blog post URL structure
permalink: /blog/:slug
