title: Aidan Loughran
tagline: Technology blog by Aidan Loughran
description: >-
  A technology blog with writings on software development,
  Linux and security & privacy advocacy.

timezone: Europe/London
lang: en
locale: en_GB

baseurl: ""
url: "loughran.dev"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

theme: minima

author:
  name: Aidan Loughran
  email: aidan@loughran.dev
  twitter: aidlran
  url: https://loughran.dev
  picture: /img/author.jpg

twitter:
  url: aidlran
  card: summary_large_image

social:
  name: Aidan Loughran
  links:
    - https://github.com/aidlran
    - https://twitter.com/aidlran
    - https://www.linkedin.com/in/aidanloughran

minima:
  skin: dark
  social_links:
    - platform: github
      user_url: https://github.com/aidlran
    - platform: linkedin
      user_url: https://github.com/aidanloughran
    - platform: twitter
      user_url: https://twitter.com/aidlran

google_analytics: G-5JY588LXRZ
show_excerpts: true

exclude:
  - lib
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - vendor
  - wishlist-config.json

permalink: /blog/:categories/:slug
