title: DistroYob
description: >-
  DistroYob is a technology blog with themes including software development,
  Linux wizardry, opsec & privacy advocacy, and cyber security.
  The DistroYob blog was created by Aidan Loughran
  to document and share the things he learns and finds valuable.

timezone: Europe/London
lang: en
locale: en_GB

baseurl: ""
url: "aidlran.github.io"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

markdown: kramdown

# theme: minima
remote_theme: jekyll/minima

author:
  name: Aidan Loughran
  email: aidlo.dev@pm.me

minima:
  skin: dark
  social_links:
    twitter: aidlran
    github: aidlran

google_analytics: G-5JY588LXRZ
show_excerpts: true

# Exclude from processing.
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md

# Blog post URL structure
permalink: /blog/:slug
