title: Aidan Loughran
tagline: Technology blog by Aidan Loughran
description: >-
  A technology blog with writings on software development,
  Linux and security & privacy advocacy.

timezone: Europe/London
lang: en
locale: en_GB

baseurl: ""
url: "aidlran.github.io"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

theme: minima

author:
  name: Aidan Loughran
  email: aidlo.dev@pm.me
  twitter: aidlran
  url: https://aidlran.github.io
  picture: /img/author.jpg

twitter:
  url: aidlran
  card: summary_large_image

social:
  name: Aidan Loughran
  links:
    - https://github.com/aidlran
    - https://twitter.com/aidlran
    - https://www.linkedin.com/in/aidan-loughran-a1a1a0243/

minima:
  skin: dark
  social_links:
    twitter: aidlran
    github: aidlran
    linkedin: aidan-loughran-a1a1a0243

google_analytics: G-5JY588LXRZ
show_excerpts: true

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - vendor
  - wishlist-config.json

include:
  - .well-known

permalink: /blog/:categories/:slug
