title: DistroYob
tagline: Technology blog by Aidan Loughran
description: >-
  DistroYob is a technology blog with themes including software development,
  Linux wizardry, opsec & privacy advocacy, and cyber security.
  The DistroYob blog was created by Aidan Loughran
  to document and share the things he learns and finds valuable.

timezone: Europe/London
lang: en
locale: en_GB

baseurl: ""
url: "aidlran.github.io"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

markdown: kramdown

# theme: minima
remote_theme: jekyll/minima

author:
  name: Aidan Loughran
  email: aidlo.dev@pm.me
  twitter: aidlran
  url: https://aidlran.github.io
  picture: /img/author.jpg

twitter:
  url: aidlran
  card: summary_large_image

social:
  name: Aidan Loughran
  links:
    - https://github.com/aidlran
    - https://twitter.com/aidlran
    - https://www.linkedin.com/in/aidan-loughran-a1a1a0243/

minima:
  skin: dark
  social_links:
    twitter: aidlran
    github: aidlran
    linkedin: aidan-loughran-a1a1a0243

google_analytics: G-5JY588LXRZ
show_excerpts: true

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md

include:
  - .well-known

permalink: /blog/:categories/:slug
