title: Aidan Loughran
tagline: Software Engineer
description: >-
  A full stack software engineer with a focus on decentralized systems, cryptography, and cybersecurity.

timezone: Europe/London
lang: en
locale: en_GB

baseurl: ""
url: "loughran.dev"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

theme: minima

author:
  name: Aidan Loughran
  url: https://loughran.dev

twitter:
  card: summary_large_image

social:
  name: Aidan Loughran
  links:
    - https://github.com/aidlran
    - https://www.linkedin.com/in/aidanloughran

minima:
  skin: dark
  social_links:
    - platform: github
      user_url: https://github.com/aidlran
    - platform: linkedin
      user_url: https://github.com/aidanloughran

google_analytics: G-5JY588LXRZ
show_excerpts: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

permalink: /blog/:categories/:slug
