name: Deploy to Pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout the commit
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Setup Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      # Install Node dependencies
      - name: Install NPM dependencies
        run: npm ci

      # Build web-wishlists
      - name: Build wishlists
        run: npm exec web-wishlist build

      # Build Jekyll site
      - name: Build Jekyll site
        run: bundle exec jekyll build

      # Setup GitHub Pages
      - name: Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v2

      # Upload GitHub Pages artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site/

  # Deploy artifact to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v1
